### ISSUE TITLE
the system cannot find the path specified

### ISSUE THREAD

**Issue by gnmarten** [o7q/Scribe#1]
would be brilliant, thx

yet, I get: "the system cannot find the path specified" when writing the txt files, txt files do not get written?
x.sctemp files get written in the storage directory, yet they are empty AFAIK
Windows with python according to specs
this seems to be a ffmpeg issue (cf. https://stackoverflow.com/questions/75644012/the-system-cannot-find-the-file-specified-error-when-trying-to-execute-ffmpeg-co)
I tried running the file with admin rights too/on drive c ...

ffmpeg version 6.1-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'G:\My Drive\ABSA_Tweets-master\01HAPNHB8BPAXHQ1KM28DYR3SD-1592574611\bennett\#TSP048 - Tom Bennett\1.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : #TSP048 - Tom Bennett
    artist          : The Two Shot Podcast
    date            : 2018
    encoder         : Lavf58.39.101
    comment         : https://www.youtube.com/watch?v=qkk0CFuc3Ew
  Duration: 00:48:02.99, start: 0.000000, bitrate: 126 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/mp3 @ 000001f772f600c0] No explicit maps, mapping streams automatically...
[aost#0:0/libmp3lame @ 000001f7714c0300] Created audio stream from input stream 0:0
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[graph_0_in_0_0 @ 000001f771531540] tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:stereo
Output #0, mp3, to 'Scribe\storage\1.m4a.mp3':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    TIT2            : #TSP048 - Tom Bennett
    TPE1            : The Two Shot Podcast
    TDRC            : 2018
    comment         : https://www.youtube.com/watch?v=qkk0CFuc3Ew
    TSSE            : Lavf60.16.100
  Stream #0:0(und): Audio: mp3, 44100 Hz, stereo, fltp, delay 1105, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.31.102 libmp3lame
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 000001f7714bb2c0] EOF while reading input
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 000001f7714bb2c0] Terminating demuxer thread
[aist#0:0/aac @ 000001f772fe6540] Decoder thread received EOF packet
[aist#0:0/aac @ 000001f772fe6540] Decoder returned EOF, finishing
[aist#0:0/aac @ 000001f772fe6540] Terminating decoder thread
No more output streams to write to, finishing.
[out#0/mp3 @ 000001f772f600c0] All streams finished
[out#0/mp3 @ 000001f772f600c0] Terminating muxer thread
[AVIOContext @ 000001f771525ec0] Statistics: 46129605 bytes written, 2 seeks, 177 writeouts
[out#0/mp3 @ 000001f772f600c0] Output file #0 (Scribe\storage\1.m4a.mp3):
[out#0/mp3 @ 000001f772f600c0]   Output stream #0:0 (audio): 110365 frames encoded (127139840 samples); 110366 packets muxed (46128483 bytes);
[out#0/mp3 @ 000001f772f600c0]   Total: 110366 packets (46128483 bytes) muxed
[out#0/mp3 @ 000001f772f600c0] video:0kB audio:45047kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001528%
size=   45048kB time=00:48:02.97 bitrate= 128.0kbits/s speed=70.5x
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 000001f7714bb2c0] Input file #0 (G:\My Drive\ABSA_Tweets-master\01HAPNHB8BPAXHQ1KM28DYR3SD-1592574611\bennett\#TSP048 - Tom Bennett\1.m4a):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 000001f7714bb2c0]   Input stream #0:0 (audio): 124160 packets read (45258713 bytes); 124160 frames decoded; 0 decode errors (127139840 samples);
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 000001f7714bb2c0]   Total: 124160 packets (45258713 bytes) demuxed
[AVIOContext @ 000001f7714c4f80] Statistics: 45816060 bytes read, 2 seeks
The system cannot find the path specified.
Could Not Find C:\Users\gnmarten\Downloads\Scribe\storage\1.m4a.txt
Press any key to continue . . .

**Comment by o7q** [comment]
It seems that whisper is not starting correctly, did you install python and the dependencies correctly? Were there any errors while you were starting Scribe for the first time?

**Comment by dmayab** [comment]
It gave me a similar error. The cause of the error was that the load_audio function uses the ffmpeg command to load and decode the audio file. It was solved by installing ffmpeg and configuring it in the system PATH.

**Comment by o7q** [comment]
FFmpeg should automatically be configured in the `PATH` when you first install Scribe, maybe it had to do with administrator privileges, if you are still having problems check the latest issue post I made. I'll make it clear in the `README` that FFmpeg needs to be installed.

**Comment by o7q** [comment]
I've added some information on FFmpeg in the `README`.

**Comment by dmayab** [comment]
Thanks for the clarification. In my case, I did not have ffmpeg installed or the path configured previously and, for some reason, probably due to the administration permissions issue, the path was not configured. By the way, I didn't say it in the previous message, thanks for the application, I'm trying it out, very interesting and useful.

**Comment by o7q** [comment]
Glad you like it! If you have anymore questions/problems please feel free to ask. Some day I need to revamp it because it's quite old and there are a lot of things I'd like to improve upon.

**Comment by o7q** [comment]
Did you have the issue on `v1.0.2.0` or `v1.0.3.0`?

**Comment by dmayab** [comment]
Excellent, I'll be attentive. I had the numpy and ffmpeg issue with version 1.0.3

**Comment by o7q** [comment]
I ended up reworking the whole program already. I fixed pretty much all the bugs related to FFmpeg + a bunch of other stuff, I listed the fixes in the changelog. Let me know how it works whenever you get around to trying it!
